name: 1. Validate Secrets

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.TEAMID }}" ]; then echo "TEAMID is missing"; exit 1; fi
          if [ -z "${{ secrets.FASTLANE_ISSUER_ID }}" ]; then echo "FASTLANE_ISSUER_ID is missing"; exit 1; fi
          if [ -z "${{ secrets.FASTLANE_KEY_ID }}" ]; then echo "FASTLANE_KEY_ID is missing"; exit 1; fi
          if [ -z "${{ secrets.FASTLANE_KEY }}" ]; then echo "FASTLANE_KEY is missing"; exit 1; fi
          if [ -z "${{ secrets.GH_PAT }}" ]; then echo "GH_PAT is missing"; exit 1; fi
          if [ -z "${{ secrets.MATCH_PASSWORD }}" ]; then echo "MATCH_PASSWORD is missing"; exit 1; fi
          if [ -z "${{ secrets.APPLE_ID }}" ]; then echo "APPLE_ID is missing"; exit 1; fi
          echo "All secrets are present!"
